In [ ]:
#Submission for ME17B158 - Omkar Nath

1) Given the array split the array at the middle (if it is odd length consider next higher integer), add reverse the array.

Ex:
if input is [12,10,5,6,52,36] 
output should be [6,52,36,12,10,5]

if input is  [12,10,5,6,52,36,34]
output should be [6,52,36,34,12,10,5]

In [1]:
import math
# Complete this function to get the desired result
def reverseatCenter(arr):
    arr2=[]
    
    i=math.floor(len(arr)/2)
    while(i<len(arr)):
        arr2.append(arr[i])
        i+=1
        
    i=0
    while(i<math.floor(len(arr)/2)):
        arr2.append(arr[i])
        i+=1
        
    return arr2

In [2]:
# Print wroking examples
print(reverseatCenter([1]))
print(reverseatCenter([1,2]))
print(reverseatCenter([1,2,3]))
print(reverseatCenter([1,2,3,4,5,6,7,8]))
print(reverseatCenter([1,2,3,4,5,6,7,8,9]))
print(reverseatCenter([]))
print(reverseatCenter([12,10,5,6,52,36]))
print(reverseatCenter([12,10,5,6,52,36,34]))

[1]
[2, 1]
[2, 3, 1]
[5, 6, 7, 8, 1, 2, 3, 4]
[5, 6, 7, 8, 9, 1, 2, 3, 4]
[]
[6, 52, 36, 12, 10, 5]
[6, 52, 36, 34, 12, 10, 5]


2) Given a list of numbers, return a list where all adjacent duplicate elements have been removed.

Ex:

2, 2, 2, 3, 2 returns 2, 3, 2.

In [3]:
# Complete the function to get the desired result
import numpy as np
def remove_adjacent(b):
    b2=[]
    i=1
    
    while(i<len(b)):
        if(b[i]!=b[i-1]):
            b2.append(b[i])
        i+=1
    
    return np.append(b[0],b2[:])

In [4]:
# Print working examples
print(remove_adjacent([2,2,2,3,2]))
print(remove_adjacent([1,1,2,3,3]))
print(remove_adjacent([1,1,1,1,2]))
print(remove_adjacent([1,2,3,4,5]))
print(remove_adjacent([1,2,1,2,1,1]))

[2 3 2]
[1 2 3]
[1 2]
[1 2 3 4 5]
[1 2 1 2 1]


3) given matrix of 7x7 full of ones, create a square with given side length (center same as original square(7x7)) replace ones with zeors at the edges for example,



$$
\begin{align}
A = \begin{bmatrix}
1 & 1 & 1 & 1 & 1 & 1 & 1\\
1 & 1 & 1 & 1 & 1 & 1 & 1\\
1 & 1 & 1 & 1 & 1 & 1 & 1\\
1 & 1 & 1 & 1 & 1 & 1 & 1\\
1 & 1 & 1 & 1 & 1 & 1 & 1\\
1 & 1 & 1 & 1 & 1 & 1 & 1\\
1 & 1 & 1 & 1 & 1 & 1 & 1\\
\end{bmatrix}
\end{align}
$$
After modification
$$
\begin{align}
A = \begin{bmatrix}
1 & 1 & 1 & 1 & 1 & 1 & 1\\
1 & 1 & 1 & 1 & 1 & 1 & 1\\
1 & 1 & 0 & 0 & 0 & 1 & 1\\
1 & 1 & 0 & 1 & 0 & 1 & 1\\
1 & 1 & 0 & 0 & 0 & 1 & 1\\
1 & 1 & 1 & 1 & 1 & 1 & 1\\
1 & 1 & 1 & 1 & 1 & 1 & 1\\
\end{bmatrix}
\end{align}
$$

In [5]:
import numpy as np
# write programm to get the desired result
def one_square(n):
    if(n>7 or n%2==0):
        return("Error")
    
    else:
        A = np.array([[1 for j in range(1,8)] for i in range(1,8)])
        
        a = math.floor((7-n)/2)
        b = math.floor((7+n)/2)
        for i in range(a,b):
            for j in range(a,b):
                A[i][j]=0
        
        if(n>1):
            a+=1
            b-=1
            for i in range(a,b):
                for j in range(a,b):
                    A[i][j]=1
                    
        return A

In [6]:
#Print working examples
print(one_square(1))
print(one_square(3))
print(one_square(5))
print(one_square(7))
print(one_square(4))
print(one_square(9))

[[1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 0 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]]
[[1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 0 0 0 1 1]
 [1 1 0 1 0 1 1]
 [1 1 0 0 0 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]]
[[1 1 1 1 1 1 1]
 [1 0 0 0 0 0 1]
 [1 0 1 1 1 0 1]
 [1 0 1 1 1 0 1]
 [1 0 1 1 1 0 1]
 [1 0 0 0 0 0 1]
 [1 1 1 1 1 1 1]]
[[0 0 0 0 0 0 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 0 0 0 0 0 0]]
Error
Error


4) Paragraph present in data.txt is encoded such that each alphabet in word is incremented to next ascii value. Decode the paragraph present in the data_encoded.txt (Hint: decrease the ascii value of each character in the word)


In [7]:
def sentence_decode(code):
    # write the code here
    dec_words = ""
    
    for i in range(len(code)):
        n = ord(code[i])
        n = ((n-1),255)[n==0]
        dec_words += chr(n)
    
    return dec_words

In [8]:
with open ("data_encoded.txt", "r") as myfile:
    data=myfile.read()
    print(data)
    print(" ")
    print(sentence_decode(data))

ebub bobmztjt jt b qspdftt pg jotqfdujoh- dmfbotjoh- usbotgpsnjoh boe npefmjoh ebub xjui uif hpbm pg ejtdpwfsjoh vtfgvm jogpsnbujpo- jogpsnjoh dpodmvtjpot boe tvqqpsujoh efdjtjpo.nbljoh/ ebub bobmztjt ibt nvmujqmf gbdfut boe bqqspbdift- fodpnqbttjoh ejwfstf ufdiojrvft voefs b wbsjfuz pg obnft- boe jt vtfe jo ejggfsfou cvtjoftt- tdjfodf- boe tpdjbm tdjfodf epnbjot/ jo upebz(t cvtjoftt xpsme- ebub bobmztjt qmbzt b spmf jo nbljoh efdjtjpot npsf tdjfoujgjd boe ifmqjoh cvtjofttft pqfsbuf npsf fggfdujwfmz/
 
dataanalysisisaprocessofinspecting,cleansing,transformingandmodelingdatawiththegoalofdiscoveringusefulinformation,informingconclusionsandsupportingdecision-making.dataanalysishasmultiplefacetsandapproaches,encompassingdiversetechniquesunderavarietyofnames,andisusedindifferentbusiness,science,andsocialsciencedomains.intoday'sbusinessworld,dataanalysisplaysaroleinmakingdecisionsmorescientificandhelpingbusinessesoperatemore

In [9]:
# Has to print the decoded paragraph.